#ifndef _CYCLOGRAM_CONFIG_H_
#define _CYCLOGRAM_CONFIG_H_

/*==GENERAL CYCLOGRAM CONSTS BEGIN==*/
#define FORWARD_SPEED 0.1
#define CELL_SIZE 0.18
/*==GENERAL CYCLOGRAM CONSTS END==*/

/*==SEARCH CONSTS BEGIN==*/
#define SEARCH_TURN_RADIUS 0.07
/*==SEARCH CONSTS END==*/

/*==SMART CYCLOGRAM CONSTS BEGIN==*/
#define SS90S_TURN_RADIUS 0.1
#define SD45S_FORW_DIST (CELL_SIZE / 4) // путь до начала поворота, максимум - CELL_SIZE / 2
#define SD135S_TURN_RADIUS 0.07
/*==SMART CYCLOGRAM CONSTS END==*/


//*==ANGLE SPEED REGULATOR BEGIN==*/
#define ANGLLE_SPEED_OPTOCOUPLER_ONESEN_REG_K 0.005 // [analogValue -> рад/с]
#define ANGLLE_SPEED_OPTOCOUPLER_TWOSEN_REG_K (0.005 + (FORWARD_SPEED * 0.05)) // [analogValue -> рад/с]  
//*==ANGLE SPEED REGULATOR END==*/



#endif // !_CYCLOGRAM_CONFIG_H_