#ifndef _CYCLOGRAM_CONFIG_H_
#define _CYCLOGRAM_CONFIG_H_

/*==GENERAL CYCLOGRAM CONSTS BEGIN==*/
#define FORWARD_SPEED 0.22
#define FAST_FORWARD_SPEED 0.22

#define FWD_SPEED_MULTIPLIER 1
#define FWDE_SPEED_MULTIPLIER 1

#define NEED_FWD_ACC 1
#if NEED_FWD_ACC
    #define FWD_ACCELERATION 0.1
#endif

#define MAX_FWD_SPEED_AFTER_ACC 0.6

#define CELL_SIZE 0.18

#define USE_ANGLE true
#define USE_ANGLE_REGULATOR true
/*==GENERAL CYCLOGRAM CONSTS END==*/

/*==SEARCH CONSTS BEGIN==*/
#define SEARCH_TURN_RADIUS 0.05
#define ANGLE_REG_EXPLORER_KP 7
/*==SEARCH CONSTS END==*/

/*==SMART CYCLOGRAM CONSTS BEGIN==*/
#define SS90S_TURN_RADIUS 0.07
#define DD90S_TURN_RADIUS 0.06 // максимум - CELL_SIZE / M_SQRT2
#define SD45S_FORW_DIST (CELL_SIZE / 2.4)// путь до начала поворота, максимум - CELL_SIZE / 2
#define SD135S_TURN_RADIUS 0.06
#define SS180S_FORW_DIST 0.11
/*==SMART CYCLOGRAM CONSTS END==*/

//*==ANGLE SPEED REGULATOR BEGIN==*/
#define ANGLE_SPEED_OPTOCOUPLER_ONESEN_REG_K (0.004 + (FORWARD_SPEED * 0.00125)) // [analogValue -> рад/с]
#define ANGLE_SPEED_OPTOCOUPLER_TWOSEN_REG_K (0.004 + (FORWARD_SPEED * 0.00125)) // [analogValue -> рад/с]  
//*==ANGLE SPEED REGULATOR END==*/

/*==ALIGNMENT CONSTS BEGIN==*/
#define ROBOT_HEIGHT 0.120
#define FROM_WHEEL_TO_SIDE 0.035

#define FROM_BACK_ALIGNMENT_TO_CENTER (HALF(CELL_SIZE) - FROM_WHEEL_TO_SIDE)
#define FROM_FORWARD_ALIGNMENT_TO_CENTER (HALF(CELL_SIZE) - (ROBOT_HEIGHT - FROM_WHEEL_TO_SIDE))

#define COLUMN_SIZE 0.012
#define FROM_HI_WALL_TO_SIDE 0.084 // 0.088
#define FROM_LO_WALL_TO_SIDE (FROM_HI_WALL_TO_SIDE - COLUMN_SIZE)

#define BACK_ALIGNMENT_TIME (HALF(CELL_SIZE)/FORWARD_SPEED * 1000 + 500) // ms
#define FORWARD_ALIGNMENT_TIME (HALF(CELL_SIZE)/FORWARD_SPEED * 1000 + 300) // ms
/*==ALIGNMENT CONSTS END==*/

/*==ANGLE REGULATOR BEGIN==*/
#define ANGLE_SPEED_GYRO_REG_KP 2.7
#define ANGLE_REG_THRESHOLD 20
/*==ANGLE REGULATOR END==*/


/*==IN PLACE ANGLE REGULATOR BEGIN==*/
#define ANGLE_REG_IN_PLACE_KP 4
#define ANGLE_REG_IN_PLACE_KI (ANGLE_REG_IN_PLACE_KP / 0.5) 
#define IP_CALIB_TIME 0.1 // c
/*==IN PLACE ANGLE REGULATOR END==*/

/*==ALIGNMENT BEGIN==*/
#define MAX_NO_ALIGN_COUNTER_DEFINE 5

/*==ALIGNMENT END==*/


#endif // !_CYCLOGRAM_CONFIG_H_